services:
  _defaults:
    autowire: true

  OxidEsales\EshopCommunity\Internal\Transition\Utility\ContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Transition\Utility\Context
    public: true

  OxidEsales\EshopCommunity\Internal\Transition\Utility\FallbackTokenGenerator:
