imports:
  - { resource: Logger/services.yaml }

services:
  _defaults:
    autowire: true
    public: false

  Doctrine\DBAL\Connection:
    factory: ['OxidEsales\EshopCommunity\Internal\Framework\Database\ConnectionFactory', get]
    class: Doctrine\DBAL\Connection

  OxidEsales\EshopCommunity\Internal\Framework\Database\QueryBuilderFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Database\QueryBuilderFactory
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Database\TransactionServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Database\TransactionService