services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Password\Bridge\PasswordServiceBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Bridge\PasswordServiceBridge
    public: true

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashServiceFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashServiceFactory

  oxid_esales.password.password_hash_bcrypt_service_options_provider:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashBcryptServiceOptionsProvider
