services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Review\Service\UserRatingServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Service\UserRatingService
  OxidEsales\EshopCommunity\Internal\Review\Service\UserReviewServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Service\UserReviewService
  OxidEsales\EshopCommunity\Internal\Review\Service\ReviewAndRatingMergingServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Service\ReviewAndRatingMergingService
  OxidEsales\EshopCommunity\Internal\Review\Service\UserReviewAndRatingServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Service\UserReviewAndRatingService
  OxidEsales\EshopCommunity\Internal\Review\Service\RatingCalculatorServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Service\RatingCalculatorService
  OxidEsales\EshopCommunity\Internal\Review\Service\ProductRatingServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Service\ProductRatingService
