parameters:
  oxid_esales.templating.engine_template_extension: 'html.twig'
  oxid_esales.templating.engine_autoescapes_html: false
  oxid_esales.templating.filter_content_tags: false

services:
  _defaults:
    autowire: true

  OxidEsales\Eshop\Core\Config:
    factory: ['OxidEsales\Eshop\Core\Registry', 'getConfig']

  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateRendererInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateRenderer
    arguments:
      $filenameExtension: '%oxid_esales.templating.engine_template_extension%'
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateRendererBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateRendererBridge
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateEngineInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateEngine

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Resolver\TemplateFileResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Templating\Resolver\TemplateFileResolver
    arguments:
      - '%oxid_esales.templating.engine_template_extension%'
    deprecated:
      package: 'oxid-esales/oxideshop-ce'
      version: '7.1.0'
      message: 'The "%service_id%" service is deprecated.'

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Locator\TemplateFileLocator:
    arguments:
      - '@OxidEsales\Eshop\Core\Config'

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Locator\AdminTemplateFileLocator:
    arguments:
      - '@OxidEsales\Eshop\Core\Config'

  oxid_esales.templating.admin.navigation.file.locator:
    class: OxidEsales\EshopCommunity\Internal\Framework\Templating\Locator\AdminNavigationFileLocator
    arguments:
      - !tagged oxid.menu.file.locator
    public: true

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Locator\EditionMenuFileLocator:
    tags:
      - { name: 'oxid.menu.file.locator', priority: 10 }
    arguments:
      Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Locator\EditionUserFileLocator:
    tags:
      - { name: 'oxid.menu.file.locator', priority: 20 }
    arguments:
      Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Cache\TemplateCacheServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Templating\Cache\TemplateCacheService
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Utility\ContextInterface'
      - '@OxidEsales\EshopCommunity\Internal\Framework\Templating\Cache\ShopTemplateCacheServiceInterface'

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Cache\ShopTemplateCacheServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Templating\Cache\ShopTemplateCacheService
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Transition\Utility\ContextInterface'
      - '@oxid_esales.symfony.file_system'

  OxidEsales\EshopCommunity\Internal\Framework\Templating\Resolver\TemplateFileResolverBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Templating\Resolver\TemplateFileResolverBridge
    public: true
    deprecated:
      package: 'oxid-esales/oxideshop-ce'
      version: '7.1.0'
      message: 'The "%service_id%" service is deprecated.'
