services:
  OxidEsales\Eshop\Core\Config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', getConfig]
    public: false

  OxidEsales\Eshop\Core\UtilsView:
    class: OxidEsales\Eshop\Core\UtilsView
    factory: ['OxidEsales\Eshop\Core\Registry', getUtilsView]
    public: false

  OxidEsales\EshopCommunity\Internal\Twig\TwigContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Twig\TwigContext
    autowire: true
    public: true

  OxidEsales\EshopCommunity\Internal\Twig\TemplateEngineConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Twig\TwigEngineConfiguration
    arguments:
        - '@OxidEsales\EshopCommunity\Internal\Twig\TwigContextInterface'
    public: true

  Symfony\Component\Templating\TemplateNameParserInterface:
    class: Symfony\Component\Templating\TemplateNameParser
    public: false

  twig.environment:
    class: Twig\Environment
    arguments:
        - '@twig.loader.chain'
        - "@=service('OxidEsales\\\\EshopCommunity\\\\Internal\\\\Twig\\\\TemplateEngineConfigurationInterface').getParameters()"
    public: false
    calls:
        - [addExtension, ['@OxidEsales\EshopCommunity\Internal\Twig\Extensions\MathExtension']]
        - [addExtension, ['@OxidEsales\EshopCommunity\Internal\Twig\Extensions\IncludeExtension']]
        - [addExtension, ['@OxidEsales\EshopCommunity\Internal\Twig\Extensions\SmartyExtension']]
        - [addExtension, ['@OxidEsales\EshopCommunity\Internal\Twig\Extensions\MailtoExtension']]
        - [addExtension, ['@OxidEsales\EshopCommunity\Internal\Twig\Extensions\UrlExtension']]
        - [addExtension, ['@OxidEsales\EshopCommunity\Internal\Twig\Extensions\AssignAdvancedExtension']]

  OxidEsales\EshopCommunity\Internal\Twig\TwigEngine:
    class: OxidEsales\EshopCommunity\Internal\Twig\TwigEngine
    arguments:
        - '@twig.environment'
        - '@Symfony\Component\Templating\TemplateNameParserInterface'
    public: false

  OxidEsales\EshopCommunity\Internal\Twig\TemplateLoaderNameParser:
    class: OxidEsales\EshopCommunity\Internal\Twig\TemplateLoaderNameParser
    public: false

# Loaders

  twig.loader.filesystem:
    class: Twig\Loader\FilesystemLoader
    arguments: ["@=service('OxidEsales\\\\EshopCommunity\\\\Internal\\\\Twig\\\\TwigContextInterface').getTemplateDirectories()"]
    public: false

  OxidEsales\EshopCommunity\Internal\Twig\Loader\ContentTemplateLoader:
    class: OxidEsales\EshopCommunity\Internal\Twig\Loader\ContentTemplateLoader
    arguments: ['@OxidEsales\EshopCommunity\Internal\Twig\TemplateLoaderNameParser']
    public: false

  twig.loader.chain:
    class: Twig\Loader\ChainLoader
    public: false
    calls:
        - [addLoader, ['@twig.loader.filesystem']]
        - [addLoader, ['@OxidEsales\EshopCommunity\Internal\Twig\Loader\ContentTemplateLoader']]


# Extensions

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\MathExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\MathExtension

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\IncludeExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\IncludeExtension

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\SmartyExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\SmartyExtension

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\MailtoExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\MailtoExtension

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\UrlExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\UrlExtension
    arguments:
        - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\SeoUrlLogic'
        - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AddUrlParametersLogic'

  OxidEsales\EshopCommunity\Internal\Twig\Extensions\AssignAdvancedExtension:
    class: OxidEsales\EshopCommunity\Internal\Twig\Extensions\AssignAdvancedExtension
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AssignAdvancedLogic'