services:
  _defaults:
    public: false
    autowire: true
  OxidEsales\EshopCommunity\Internal\Application\Service\ProjectYamlImportServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Application\Service\ProjectYamlImportService
    public: true
