services:

  Doctrine\DBAL\Connection:
    factory: ['OxidEsales\EshopCommunity\Internal\Common\Factory\ConnectionFactory', get]
    class: Doctrine\DBAL\Connection
    public: false
  OxidEsales\EshopCommunity\Internal\Common\Database\QueryBuilderFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\Database\QueryBuilderFactory
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Common\Database\TransactionServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\Database\TransactionService
    autowire: true
    public: false

  common.form.required_fields_validator:
    class: OxidEsales\EshopCommunity\Internal\Common\Form\RequiredFieldsValidator
    autowire: true
    public: false

  oxid_esales.common.storage.flock_store_lock_factory:
    class: Symfony\Component\Lock\Factory
    arguments:
      - '@oxid_esales.common.storage.flock_store'

  oxid_esales.common.storage.flock_store:
    class: Symfony\Component\Lock\Store\FlockStore

  OxidEsales\EshopCommunity\Internal\Common\CopyGlob\CopyGlobServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\CopyGlob\CopyGlobService
    autowire: true

  oxid_esales.symfony.file_system:
    class: Symfony\Component\Filesystem\Filesystem
