services:
  _defaults:
    autowire: true
    public: false

  Doctrine\DBAL\Connection:
    factory: ['OxidEsales\EshopCommunity\Internal\Common\Database\ConnectionFactory', get]
    class: Doctrine\DBAL\Connection

  OxidEsales\EshopCommunity\Internal\Common\Database\QueryBuilderFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\Database\QueryBuilderFactory
    autowire: true

  OxidEsales\EshopCommunity\Internal\Common\Database\TransactionServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\Database\TransactionService

  common.form.required_fields_validator:
    class: OxidEsales\EshopCommunity\Internal\Common\Form\RequiredFieldsValidator
