services:

  Doctrine\DBAL\Connection:
    factory: ['OxidEsales\EshopCommunity\Internal\Common\Factory\ConnectionFactory', get]
    class: Doctrine\DBAL\Connection
    public: false
  OxidEsales\EshopCommunity\Internal\Common\Database\QueryBuilderFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\Database\QueryBuilderFactory
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Common\Form\FormBuilderInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\Form\FormBuilder
    autowire: true
    public: false

  common.form.required_fields_validator:
    class: OxidEsales\EshopCommunity\Internal\Common\Form\RequiredFieldsValidator
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface:
      class: OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDao
      autowire: true
      public: false
