services:
  _defaults:
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Logger\Validator\LoggerConfigurationValidatorInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Validator\PsrLoggerConfigurationValidator
  OxidEsales\EshopCommunity\Internal\Logger\Configuration\MonologConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Configuration\MonologConfiguration
    arguments:
      $loggerName: 'OXID Logger'
      $context: '@OxidEsales\EshopCommunity\Internal\Utility\ContextInterface'
  OxidEsales\EshopCommunity\Internal\Logger\Factory\LoggerFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Factory\MonologLoggerFactory
  Monolog\Logger:
    class: Monolog\Logger
    factory: 'OxidEsales\EshopCommunity\Internal\Logger\Factory\LoggerFactoryInterface:create'
  Psr\Log\LoggerInterface:
    class: OxidEsales\EshopCommunity\Internal\Logger\Wrapper\LoggerWrapper
    arguments:
      $logger: '@Monolog\Logger'
    public: true
