imports:
   - { resource: Configuration/services.yaml }
   - { resource: Facade/services.yaml }
   - { resource: Setup/services.yaml }
   - { resource: Cache/services.yaml }
   - { resource: TemplateExtension/services.yaml }
   - { resource: Setting/services.yaml }
   - { resource: State/services.yaml }
   - { resource: Install/services.yaml }
   - { resource: Command/services.yaml }
   - { resource: Path/services.yaml }
   - { resource: Template/services.yaml }
   - { resource: Translation/services.yaml }
