services:
  _defaults:
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Container\Dao\ProjectYamlDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Container\Dao\ContainerAwareProjectYamlDao
    arguments:
      Symfony\Component\Filesystem\Filesystem: '@oxid_esales.symfony.file_system'
