services:
  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleActivationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleActivationService
    autowire: true
    arguments:
      $classExtensionChainService: '@oxid_esales.module.setup.class_extension_chain_service'

  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleSettingsHandlingServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleSettingsHandlingService
    autowire: true
    calls:
      - [addHandler, ['@oxid_esales.module.setup.path_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.version_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.templates_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.controllers_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.smarty_plugin_directories_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.class_extensions_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.template_blocks_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.shop_module_setting_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.events_module_setting_handler']]
      - [addValidator, ['@oxid_esales.module.setup.validator.controllers_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.smarty_plugin_directories_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.class_extensions_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.events_module_setting_validator']]

  oxid_esales.module.setup.version_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::VERSION
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_VERSIONS
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.path_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::PATH
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_PATHS
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.templates_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::TEMPLATES
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_TEMPLATES
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.controllers_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ControllersModuleSettingHandler
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.smarty_plugin_directories_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::SMARTY_PLUGIN_DIRECTORIES
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_SMARTY_PLUGIN_DIRECTORIES
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.class_extensions_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ClassExtensionsModuleSettingHandler
    autowire: true

  oxid_esales.module.setup.template_blocks_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\TemplateBlockModuleSettingHandler
    autowire: true

  oxid_esales.module.setup.shop_module_setting_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopModuleSettingModuleSettingHandler
    autowire: true

  oxid_esales.module.setup.events_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::EVENTS
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_EVENTS
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.validator.smarty_plugin_directories_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\SmartyPluginDirectoriesModuleSettingValidator
    autowire: true

  oxid_esales.module.setup.validator.controllers_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\ControllersModuleSettingValidator
    autowire: true

  oxid_esales.module.setup.validator.class_extensions_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\ClassExtensionsModuleSettingValidator
    autowire: true

  oxid_esales.module.setup.validator.events_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\EventsModuleSettingValidator
    autowire: true

  oxid_esales.module.setup.service.eventsubscriber.after_module_activation_event_subscriber:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\EventSubscriber\AfterModuleActivationSubscriber
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Module\Configuration\Dao\ModuleConfigurationDaoInterface'
    tags:
      - { name: kernel.event_subscriber }

  oxid_esales.module.setup.service.eventsubscriber.before_module_deactivation_event_subscriber:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\EventSubscriber\BeforeModuleDeactivationSubscriber
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Module\Configuration\Dao\ModuleConfigurationDaoInterface'
    tags:
      - { name: kernel.event_subscriber }

  oxid_esales.module.setup.class_extension_chain_service:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ClassExtensionChainService
    autowire: true

  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ActiveClassExtensionChainResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ActiveClassExtensionChainResolver
    autowire: true