services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Module\Setup\Bridge\ModuleActivationBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Bridge\ModuleActivationBridge
    public: true

  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleActivationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleActivationService
    arguments:
      $classExtensionChainService: '@oxid_esales.module.setup.class_extension_chain_service'

  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleConfigurationHandlingServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleConfigurationHandlingService
    calls:
      - [addHandler, ['@oxid_esales.module.setup.path_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.templates_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.controllers_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.smarty_plugin_directories_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.class_extensions_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.template_blocks_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.shop_module_setting_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.events_module_setting_handler']]
      - [addHandler, ['@oxid_esales.module.setup.files_without_namespace_module_setting_handler']]
      - [addValidator, ['@oxid_esales.module.setup.validator.controllers_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.smarty_plugin_directories_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.class_extensions_module_setting_validator']]
      - [addValidator, ['@oxid_esales.module.setup.validator.events_module_setting_validator']]

  oxid_esales.module.setup.path_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ModulePathHandler

  oxid_esales.module.setup.templates_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::TEMPLATES
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_TEMPLATES
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.controllers_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ControllersModuleSettingHandler
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.smarty_plugin_directories_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::SMARTY_PLUGIN_DIRECTORIES
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_SMARTY_PLUGIN_DIRECTORIES
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.class_extensions_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ClassExtensionsModuleSettingHandler

  oxid_esales.module.setup.template_blocks_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\TemplateBlockModuleSettingHandler

  oxid_esales.module.setup.shop_module_setting_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopModuleSettingModuleSettingHandler

  oxid_esales.module.setup.events_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::EVENTS
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_EVENTS
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.files_without_namespace_module_setting_handler:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Handler\ShopConfigurationModuleSettingHandler
    arguments:
      - !php/const OxidEsales\EshopCommunity\Internal\Module\Configuration\DataObject\ModuleSetting::CLASSES_WITHOUT_NAMESPACE
      - !php/const OxidEsales\EshopCommunity\Internal\Adapter\Configuration\DataObject\ShopConfigurationSetting::MODULE_CLASSES_WITHOUT_NAMESPACES
      - '@OxidEsales\EshopCommunity\Internal\Adapter\Configuration\Dao\ShopConfigurationSettingDaoInterface'

  oxid_esales.module.setup.validator.smarty_plugin_directories_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\SmartyPluginDirectoriesModuleSettingValidator

  oxid_esales.module.setup.validator.controllers_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\ControllersModuleSettingValidator

  oxid_esales.module.setup.validator.class_extensions_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\ClassExtensionsModuleSettingValidator

  oxid_esales.module.setup.validator.events_module_setting_validator:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Validator\EventsModuleSettingValidator

  oxid_esales.module.setup.service.eventsubscriber.dispatch_legacy_events_subscriber:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\EventSubscriber\DispatchLegacyEventsSubscriber
    tags:
      - { name: kernel.event_subscriber }

  oxid_esales.module.setup.service.eventsubscriber.event_logging_subscriber:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\EventSubscriber\EventLoggingSubscriber
    tags:
      - { name: kernel.event_subscriber }

  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleServicesActivationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ModuleServicesActivationService
    public: true

  oxid_esales.module.setup.class_extension_chain_service:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ClassExtensionChainService

  OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ActiveClassExtensionChainResolverInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setup\Service\ActiveClassExtensionChainResolver
