services:
  _defaults:
    autowire: true

  Symfony\Component\EventDispatcher\EventDispatcherInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Event\ShopAwareEventDispatcher
    public: true
