services:
  _defaults:
    autowire: true
    public: false

  oxid_esales.review.product_rating_mapper:
    class: OxidEsales\EshopCommunity\Internal\Review\DataMapper\ProductRatingDataMapper
    public: false
  oxid_esales.review.rating_mapper:
    class: OxidEsales\EshopCommunity\Internal\Review\DataMapper\RatingDataMapper
    public: false
  oxid_esales.review.review_mapper:
    class: OxidEsales\EshopCommunity\Internal\Review\DataMapper\ReviewDataMapper
    public: false
