services:
  _defaults:
    public: false
    autowire: true
  OxidEsales\EshopCommunity\Internal\Container\Service\ProjectYamlImportServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Container\Service\ProjectYamlImportService
    public: true

  OxidEsales\EshopCommunity\Internal\Container\Service\ShopStateServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Container\Service\ShopStateService
    arguments:
      $anyUnifiedNamespace: '\OxidEsales\Eshop\Core\Registry'
    public: true
